services:
  - type: web
    name: olms
    runtime: node
    plan: free
    buildCommand: npm install && npx prisma generate && npx prisma db push && node prisma/seed.js && npm run build
    startCommand: NODE_ENV=production node .next/standalone/server.js
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        value: file:./db/custom.db
