services:
  - type: web
    name: olms
    runtime: node
    plan: free
<<<<<<< HEAD
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npx prisma db push && node prisma/seed.js && NODE_ENV=production node .next/standalone/server.js
=======
    buildCommand: npm install && npx prisma generate && npx prisma db push && node prisma/seed.js && npm run build
    startCommand: NODE_ENV=production node .next/standalone/server.js
>>>>>>> 04eb435d1a6e92ce3425f7e254d5829ee4bdb0c7
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
<<<<<<< HEAD
        value: file:/opt/render/project/src/.data/custom.db
=======
        value: file:./db/custom.db
>>>>>>> 04eb435d1a6e92ce3425f7e254d5829ee4bdb0c7
